language: go
install: go get -t -d -v ./... && go build -v ./...
go:
- 1.2
- 1.3
notifications:
  slack:
    secure: RHxSwdNsJLAtKQ5ZmHe+63DY5ZFDFsJOHINbfehQKCsHp211kqKiJoPXTxfdBk4GGr7bsmmtROh60FFzCJ0JZ2NbNIgZDSFkdIMfcl9AG0aAII4LLycvJZn1Qq2FZbytM2/v+j1J+15sQ4mLXZ/2Zs9UhvB7dkgjMjvGbd2Oc4g=
  email: false
